### ISSUE TITLE
Updated README on how to run the program

### ISSUE THREAD

**Issue by syedalisait** [noculture/notes#1]
Can you please include instructions in README on how the notebook works with some examples?

**Comment by ifennna** [comment]
Hi @syedalisait, thanks for raising this!

I've updated the README to provide more info. Feel free to mention if you need anything else.

**Comment by syedalisait** [comment]
@noculture 
Thanks for adding. Would you be willing to accept pull requests for delete notebook/note?

**Comment by ifennna** [comment]
That would be great @syedalisait. I definitely would.

**Comment by syedalisait** [comment]
Closing this issue. Thank you @noculture
