### ISSUE TITLE
List notes by notebook works by prefix

### ISSUE THREAD

**Issue by mzampetakis** [noculture/notes#12]
When using the 'ls' command the provided notebook name can be a prefix of any notebook and not the exact notebook's name as expected.
Moreover, if there are more that one notebooks with the same prefix the older created one is chosen.

Should the `ls` command work only with the exact match?

**Comment by ifennna** [comment]
I think the expected behavior of `ls` would be to work with the exact match of a notebook name. Bash completion would probably be a better fit for what you have in mind. Plus it wouldn't just be limited to the `ls` command.

**Comment by y2k-shubham** [comment]
Yes @noculture & @mzampetakis , the prefix match behaviour was replaced with exact match in this PR https://github.com/noculture/notes/pull/8#issue-399250790; here's the relevant link from code https://github.com/noculture/notes/pull/8/files#diff-df4f8f55c70b36f10a9b798e559408a6R53

**Comment by mzampetakis** [comment]
Nice @y2k-shubham ! This issue can be closed imo.
