### ISSUE TITLE
AddNote should accept note's Content only

### ISSUE THREAD

**Issue by y2k-shubham** [noculture/notes#13]
- from user perspective, [`AddNote()`](https://github.com/noculture/notes/blob/master/models/db.go#L20) should be accepting only a text message - the `Content` of `Note` rather than a `Note` object
 - furthermore, this would be in-line with the remaining methods in our current design. In [`DeleteNote` method](https://github.com/noculture/notes/blob/master/models/note.go#L42) for example, we only accept notebook-name & noteId (rather than `Note` object)
 - even in the current implementation, we [only really pass the `Content`](https://github.com/noculture/notes/blob/master/cmd/add.go#L23) within the `Note` object and [generate the `Id`](https://github.com/noculture/notes/blob/master/models/note.go#L25) from within the method

**Comment by ifennna** [comment]
This makes sense. I guess the method changed over time but its signatures have not.

**Comment by ifennna** [comment]
This has been handled in PR #24
