### ISSUE TITLE
Function that project doesn't use 

### ISSUE THREAD

**Issue by plug-1n** [noculture/notes#40]
There is a func named Register(cmd *cobra.Command) in _notes/cmd/root_. I was trying to find the line of code where it was used, but i found no one.  I could be wrong, but init function initialize when project builds and usual function doesn't.

**Comment by plug-1n** [comment]
Correct me if I'm wrong

**Comment by ifennna** [comment]
Sorry for the late response @plug-1n. You're right. This function is no longer used. I'm taking it out.
